# Numpy Practice

In [1]:
import numpy as np

## Array
**np.array (object, dtype=None, copy=True, order=None, subok=False, ndmin = 0)**

In [2]:
# one dimentional array
a = np.array([1,2])
print (a)

[1 2]


In [3]:
# Two dimentional array
a = np. array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
a = np.array([1,2,3,4], ndmin = 1)
print(a)

[1 2 3 4]


In [5]:
a = np.array([1,2,3,4], ndmin = 2)
print(a)

[[1 2 3 4]]


In [6]:
a = np.array([1,2,3,4], ndmin = 3)
print(a)

[[[1 2 3 4]]]


In [7]:
a = np.array ([1,2,3],ndmin=1, dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [8]:
a = np.array ([1,2,3], ndmin=2, dtype=complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]]


In [9]:
a = np.array ([[1,2,3],[4,5,6]],ndmin=2, dtype=complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


**Data Types**

In [10]:
dt = np.dtype(np.int32)
print(dt)

int32


In [11]:
dt1 = np.dtype('i1')
dt2 = np.dtype('i2')
dt3 = np.dtype('i4')
dt4 = np.dtype('i8')
print(dt1)
print(dt2)
print(dt3)
print(dt4)

int8
int16
int32
int64


In [12]:
dt = np.dtype([('age', 'i1')])
print(dt)

[('age', 'i1')]


In [13]:
dt = np.dtype([('age', 'i1')])
a = np.array([1,2,3,4], dtype = dt)
print(a)

[(1,) (2,) (3,) (4,)]


In [14]:
dt = np.dtype([('age', 'i1')])
a = np.array([1,2,3,4],dtype =dt)
print(a['age'])

[1 2 3 4]


In [15]:
# students = np.dtype ([('name', (20,), ('age', 1i), ('marks', f4)])
# a = np.array([('abc',21,50),('xyz', 30, 25)], dtype = students)
# print(a)

**Array Attributes**

In [16]:
a =np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
a =np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
a = np.arange(12)
b= a.reshape(2,3,2)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [20]:
x =np.array([1,2,3,4,5])
print(x.itemsize)

4


In [21]:
x =np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [22]:
x = np.zeros((2,2), dtype = [('x', 'i1'), ('y', 'i1')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [28]:
s = 'Hello World'
a = np.frombuffer(s, dtype ='S1')
print(a)

TypeError: a bytes-like object is required, not 'str'