# Numpy

In [1]:
import numpy as np

In [2]:
a = np. array([[3,2,1], [1,2,3]])

In [3]:
b = np. array ([[5,2,1],[3,5,4]])

In [10]:
c = a - b

In [12]:
c

array([[-2,  0,  0],
       [-2, -3, -1]])

In [7]:
np.save('my_array',c)

In [11]:
np.load('my_array.npy')

array([[-2,  0,  0],
       [-2, -3, -1]])

In [14]:
len (a)

2

In [16]:
c.ndim

2

In [17]:
a


array([[3, 2, 1],
       [1, 2, 3]])

In [18]:
a.T

array([[3, 1],
       [2, 2],
       [1, 3]])

In [21]:
a.sum()

12

In [22]:
np.sqrt(a)

array([[1.73205081, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.73205081]])

In [26]:
np.exp(a)

array([[20.08553692,  7.3890561 ,  2.71828183],
       [ 2.71828183,  7.3890561 , 20.08553692]])

In [31]:
np.tan(0)

0.0

In [32]:
a

array([[3, 2, 1],
       [1, 2, 3]])

In [34]:
b= a. ravel()

In [35]:
b

array([3, 2, 1, 1, 2, 3])

In [38]:
b.reshape(6,1)

array([[3],
       [2],
       [1],
       [1],
       [2],
       [3]])

In [41]:
b.reshape(6,)

array([3, 2, 1, 1, 2, 3])